# Use postgres/example user/password credentials
version: '3.1'

services:
  rastreator:
    build: ./src/
    command:  bash -c "invoke install && invoke start"    
    volumes:
      - ./src:/src
    ports:
      - 8000:8000